Milestone 2: Implemented the CRUD methods
prg-04/To-Do_List pull request #2
Opened 2023-05-12 17:32 UTC by prg-04

### I have done the following to reach this milestone:

- [ ] Removed hardcoded items in the tasks array
- [ ] Implemented the functions for adding and removing an element from the list
- [ ] Added an Editing function
- [ ] Set the completed property of the List to be toggled to true or false based on whether the taks is completed
- [ ] Dynamically update the index when a task is added or removed

2023-05-12 17:51 UTC, youmari requested changes
Hi @prg-04 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 17:51 UTC, youmari commented on src/store.js
>    }
- [ ] When I tried to remove a task the whole application freezes and doesn't respond anymore so please make sure to fix this issue to complete the requirements 
<img width="1440" alt="Screenshot 2023-05-12 at 18 48 35" src="https://github.com/prg-04/To-Do_List/assets/61790587/98de3a9c-e2d0-449d-88df-77d67f770f27">

2023-05-13 10:48 UTC, frank1738 requested changes
Hi @prg-04 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 10:48 UTC, frank1738 commented on src/index.js
> +  task.addList(list);
- [ ] Currently, the problem with deleting items from your todo app persists, kindly check out this [video](https://www.youtube.com/watch?v=AcUd-_Yjjqg) to guide  you on how the functionality works

2023-05-13 12:07 UTC, enniopo commented
Hi @prg-04 your dashboard has been updated and you can now request another code review once you are done implementing the changes requested by  @frank1738 . 
Apologies for any inconvenience caused.

2023-05-13 15:08 UTC, Ginohmk requested changes
Hi @prg-04 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![keep-trying-youre-almost-there](https://user-images.githubusercontent.com/67087664/169483884-c624db70-793d-42be-8ebe-afef6a1cd5c3.gif)

 ## Highlights
- Linters passed :100: 
- Good file organization :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 15:08 UTC, Ginohmk commented on src/task.js
> +
- Hi @prg-04 , I noticed, the change requested by the previous code reviewer was not implemented, as the window freezes when ever i try performing delete item is operation. 

- I went through your code base and discovered the source of the issue, is in your `for loop` you incremented your `i` as thus `i + 1` which results in an error but changing it to `i += 1` fixes the issue. Please make the appropriate changes to your code base. 

```javascript
 removeList(id) {
    const index = this.items.findIndex((item) => item.id === id);
    if (index !== -1) {
      this.items.splice(index, 1);
      for (let i = index; i < this.items.length; i += 1) {
        this.items[i].id = i + 1;
      }
      this.store.setItems(this.items);
      this.updateList();
    }
  }
```

2023-05-13 15:25 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @prg-04 

Your project is complete! Great job for implementing the changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- CRUD  methods ok
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/a0Lgc1JvbfS4o/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 15:27 UTC, merged